[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
avax_mainnet = "https://api.avax.network/ext/bc/C/rpc"
